
import type { Metadata } from "next";
import "./globals.css";
// import Navbar from './../Components/Navbar/Navbar';
import Sidebar from './../Components/Navbar/Sidebar';
import { Suspense } from "react";
import Loading from './../Components/Loading';
import AuthStorage from "@/context.jsx/AuthStorage";




export const metadata: Metadata = {
  title: "Duah",
  description: "Generated by create Mishkat",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="font-raleway" >
        <AuthStorage>
          <Suspense fallback={<Loading />}>
            {/* {/* <Navbar /> */}
            <div className="grid grid-cols-5">
              <div className="col-span-1 bg-main  h-[calc(100vh-68px)]">
                <div className="h-[1px] w-full bg-secondary opacity-20 shadow-md"></div>
                <Sidebar />
              </div>
              <div className="col-span-4 shadow-md">
                {children}
              </div>
            </div>
          </Suspense>
        </AuthStorage>
      </body>
    </html >
  );
}

// h-[calc(100vh-9vh)]
